spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  thymeleaf:
    cache: false
server:
  port: 8080


